[[rules]]
version = '>=4, <5'
patch = 'pytest-4.patch'
subdir = 'src'

[[rules]]
version = '>=5, <6'
patch = 'pytest-5.patch'
subdir = 'src'

[[rules]]
version = '>=6, <7'
patch = 'pytest-6.patch'
subdir = 'src'

[[rules]]
install-priority = 10
version = '>=7'
patch = 'pytest-7.patch'
subdir = 'src'
