[[rules]]
version = '== 1.13.1'
patch = 'torch-1.13.1.patch'
dist-type = 'sdist'

[[add-sources]]
version = '1.13.1'
url = 'https://github.com/pytorch/pytorch/releases/download/v1.13.1/pytorch-v1.13.1.tar.gz'
