name: Build for Windows (x64)
on: [push, pull_request]
permissions:
  contents: write

jobs:
  build:
    name: Build for Windows (x64)
    runs-on: windows-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v4

      # Setup the Windows build environment
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      # Set up GraalVM for non-Maven projects
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maven-version: '3.8.8'

      # Create a staging directory where the binary will be copied into
      - name: Make staging directory
        run: mkdir staging

      # Build your project using Maven with GraalVM
      # The desktop profile is used, which means a native build will be created for the host platform (in this case Linux) itself.
      - name: Gluon Build
        run: ./mvnw.cmd gluonfx:build

      # Copy the native binary to the staging directory
      - name: Copy native image to staging
        run: |
          cp -r target/gluonfx/x86_64-windows/FMAchipelagoTracker.exe staging
          cp -r resources staging
          cp LICENSE.txt staging

      # Upload the staging directory as a build artifact. You will be able to download this after the build finishes.
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: staging

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Zip artifacts
        run: zip -r FMArchipelagoTracker-windows.zip windows-x64

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          prerelease: false
          draft: false
          files: FMArchipelagoTracker-windows.zip
          generate_release_notes: false
          make_latest: 'legacy'
          body: |
            Legacy release for v1 `apworld`s. **Do not use unless you're on a v1 `apworld` from over a year ago**. For recent `apworld`s, use the [latest release](https://github.com/sg4e/FMArchipelagoTracker/releases/latest) instead.
            
            Windows (x64) build of the Yu-Gi-Oh! Forbidden Memories Archipelago Tracker. If you get errors about missing `.dll`s when running, install the [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe).
